name: Construir una App en Next.JS
on: push
permissions:
  contents: write
jobs:
    build-project:
      name: Construccion de Proyecto
      runs-on: ubuntu-latest
      steps:
        - name: Checkout del código
          uses: actions/checkout@v4
        - name: Instalar dependencias
          run: npm install
        - name: Ejecutar en produccion
          run: npm run build
        - name: Desplegar en GitHub PAges
          uses: JamesIves/github-pages-deploy-action@v4
          with:
            branch: main
            folder: .next


