name: Construir una App en Next.JS
on: push
jobs:
    build-project:
      name: Construccion de Proyecto
      runs-on: ubuntu-latest
      steps:
        - name: Checkout del código
          uses: actions/checkout@v4
        - name: Instalar dependencias
          run: npm install
        - name: Ejecutar en produccion
          run: npm run build
        - name: Crear un artefacto
          uses: actions/upload-artifact@v4
          with:
            name: Artefacto 1
            path: .next/
        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@v4
          with:
            branch: main
            folder: .next
    release-project:
      name: Despliegue de Proyecto
      runs-on: ubuntu-latest
      needs: build-project
      steps:
        - name: Crear directorio de descargas
          run: mkdir download
        - uses: actions/download-artifact@v4
          with:
            name: Artefacto 1
            path: download
        - name: Mostrar estructura del proyecto
          run: ls -R

